### ISSUE TITLE
Peer-To-Peer Feedback

### ISSUE THREAD

**Issue by skyv26** [PraisesPJMT/Leaderboard#4]
# Hi @PraisesPJMT 👋🏻 ,

Your work is impressive and I liked your file structure you did a really good job without any doubt. But still, there are some areas where you need to more focus and make some changes.

## Issue 📝 

- Please look at the below snippets so that you can tweak your `HTML`. Please follow the Best Practices of HTML
https://github.com/PraisesPJMT/Leaderboard/blob/196d1a989aac9b5b29c492a6af2ea49c763241e5/src/index.html#L25-L38

- Please also use `class name` for all tags instead of styling them directly with tagName
https://github.com/PraisesPJMT/Leaderboard/blob/196d1a989aac9b5b29c492a6af2ea49c763241e5/src/styles.css#L10-L20

- Please try to use only either `then` promise to resolve function *OR* please use `async` and `await` because mixing two things into one is not a good idea and not feasible too.
https://github.com/PraisesPJMT/Leaderboard/blob/196d1a989aac9b5b29c492a6af2ea49c763241e5/src/index.js#L22-L33

- Please try-catch the block at the time of function implementation.

Well at last I would say **GREAT** work and I appreciate your work and efforts best wishes for the future. Good Luck!

Happy Coding 🥂

**Comment by PraisesPJMT** [comment]
Thanks for the issue!
